spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ykn12345
    url: jdbc:mysql://192.168.37.129:3306/opera_tube
  redis:
    host: 192.168.37.129
    port: 6379 # 配置使用redis作为缓存
  session:
    store-type: redis
    timeout: 30m
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.37.129:8848
  application:
    name: operatube-video
  thymeleaf:
    cache: false
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    com.sovava: debug
server:
  port: 8088
operatube:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10